using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using CRM.Api.Data;
using CRM.Api.Models;
using CRM.Api.Services;

var builder = WebApplication.CreateBuilder(args);

// Database: auto-detect PostgreSQL vs SQLite
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")!;
if (connectionString.Contains("Host=") || connectionString.Contains("Server="))
{
    builder.Services.AddDbContext<ApplicationDbContext>(options => options.UseNpgsql(connectionString));
}
else
{
    builder.Services.AddDbContext<ApplicationDbContext>(options => options.UseSqlite(connectionString));
}

builder.Services.AddIdentity<ApplicationUser, IdentityRole>(options =>
{
    options.Password.RequireDigit = true;
    options.Password.RequireLowercase = false;
    options.Password.RequireUppercase = false;
    options.Password.RequireNonAlphanumeric = false;
    options.Password.RequiredLength = 6;
    options.User.RequireUniqueEmail = true;
    options.SignIn.RequireConfirmedAccount = false;
}).AddEntityFrameworkStores<ApplicationDbContext>().AddDefaultTokenProviders();

var jwtKey = builder.Configuration["Jwt:Key"]
    ?? builder.Configuration["Jwt__Key"]
    ?? throw new InvalidOperationException("JWT key not configured");
var jwtIssuer = builder.Configuration["Jwt:Issuer"]
    ?? builder.Configuration["Jwt__Issuer"]
    ?? "crm.visionplusapps.com";
var jwtAudience = builder.Configuration["Jwt:Audience"]
    ?? builder.Configuration["Jwt__Audience"]
    ?? "crm.visionplusapps.com";

builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = jwtIssuer,
        ValidAudience = jwtAudience,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey))
    };
});

builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("AdminOnly", p => p.RequireRole("Administrator"));
    options.AddPolicy("ManagerOrAdmin", p => p.RequireRole("Administrator", "Manager"));
});

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "CRM API", Version = "v1" });
    c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Description = "JWT Authorization header using the Bearer scheme",
        Name = "Authorization",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.ApiKey,
        Scheme = "Bearer"
    });
    c.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" }
            },
            Array.Empty<string>()
        }
    });
});

builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        var origins = builder.Configuration["AllowedOrigins"]?.Split(',') ?? new[] { "*" };
        policy.WithOrigins(origins)
            .AllowAnyMethod()
            .AllowAnyHeader()
            .AllowCredentials();
    });
});

builder.Services.AddHttpClient<IWhatsAppService, WhatsAppService>(client =>
{
    client.Timeout = TimeSpan.FromSeconds(30);
});
builder.Services.AddHealthChecks();

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
    await db.Database.EnsureCreatedAsync();

    // Lightweight schema patch for existing databases that were created
    // before the Address/City columns (and the City table + FK) were added.
    // Safe to re-run: each statement is idempotent or wrapped in try/catch.
    var isPg = !string.IsNullOrEmpty(connectionString) && connectionString.Contains("Host=");
    if (isPg)
    {
        try
        {
            await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Leads\" ADD COLUMN IF NOT EXISTS \"Address\" text;");
            await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Leads\" ADD COLUMN IF NOT EXISTS \"City\" text;");
            await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Leads\" ADD COLUMN IF NOT EXISTS \"CityId\" integer;");
            await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS \"Cities\" (\"Id\" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, \"Name\" text NOT NULL, \"IsActive\" boolean NOT NULL DEFAULT true, \"CreatedAt\" timestamp with time zone NOT NULL);");
            await db.Database.ExecuteSqlRawAsync("CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Cities_Name\" ON \"Cities\" (\"Name\");");
            await db.Database.ExecuteSqlRawAsync("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Leads_Cities_CityId') THEN ALTER TABLE \"Leads\" ADD CONSTRAINT \"FK_Leads_Cities_CityId\" FOREIGN KEY (\"CityId\") REFERENCES \"Cities\"(\"Id\") ON DELETE SET NULL; END IF; END $$;");
        }
        catch { /* column/constraint already exists or not supported — ignore */ }

        // Backfill: ensure 40 Pakistani cities exist in the Cities table.
        // Uses ON CONFLICT DO NOTHING so it's a no-op if the data is already there.
        try
        {
            var cityNames = new[]
            {
                "Karachi","Lahore","Islamabad","Rawalpindi","Faisalabad","Multan","Peshawar","Quetta","Sialkot","Gujranwala",
                "Hyderabad","Bahawalpur","Sargodha","Sukkur","Larkana","Sheikhupura","Rahim Yar Khan","Jhang","Dera Ghazi Khan","Gujrat",
                "Sahiwal","Wah Cantonment","Mardan","Kasur","Mingora","Nawabshah","Chiniot","Kotri","Bannu","Abbottabad",
                "Muzaffargarh","Mirpur Khas","Turbat","Jacobabad","Shikarpur","Kohat","Khuzdar","Dera Ismail Khan","Charsadda","Nowshera"
            };
            foreach (var n in cityNames)
            {
                await db.Database.ExecuteSqlRawAsync(
                    "INSERT INTO \"Cities\" (\"Name\", \"IsActive\", \"CreatedAt\") SELECT @n, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM \"Cities\" WHERE LOWER(\"Name\") = LOWER(@n));",
                    new Npgsql.NpgsqlParameter("@n", n));
            }
        }
        catch { /* ignore seed failures — data may already be present */ }
    }
    else
    {
        try
        {
            await db.Database.ExecuteSqlRawAsync("ALTER TABLE Leads ADD COLUMN Address TEXT;");
            await db.Database.ExecuteSqlRawAsync("ALTER TABLE Leads ADD COLUMN City TEXT;");
            await db.Database.ExecuteSqlRawAsync("ALTER TABLE Leads ADD COLUMN CityId INTEGER;");
            await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS Cities (Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL, IsActive INTEGER NOT NULL DEFAULT 1, CreatedAt TEXT NOT NULL);");
            await db.Database.ExecuteSqlRawAsync("CREATE UNIQUE INDEX IF NOT EXISTS IX_Cities_Name ON Cities (Name);");
        }
        catch { /* column already exists or not supported — ignore */ }
    }

    await SeedDataService.SeedAsync(scope.ServiceProvider);
}

var uploadsPath = Path.Combine(app.Environment.WebRootPath, "uploads", "profiles");
Directory.CreateDirectory(uploadsPath);

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseCors();
app.UseStaticFiles();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();
app.MapHealthChecks("/health");

app.Run();
