- generic [active] [ref=e1]:
  - generic [ref=e3]:
    - complementary [ref=e4]:
      - generic [ref=e5]:
        - img [ref=e6]
        - generic [ref=e8]: CRM System
      - navigation [ref=e9]:
        - generic [ref=e10]:
          - link "Dashboard" [ref=e11] [cursor=pointer]:
            - /url: /
            - img [ref=e12]
            - text: Dashboard
          - link "Leads" [ref=e17] [cursor=pointer]:
            - /url: /leads
            - img [ref=e18]
            - text: Leads
          - link "Messages" [ref=e23] [cursor=pointer]:
            - /url: /messages
            - img [ref=e24]
            - text: Messages
        - generic [ref=e26]:
          - paragraph [ref=e27]: Analytics
          - generic [ref=e28]:
            - link "Reports" [ref=e29] [cursor=pointer]:
              - /url: /reports
              - img [ref=e30]
              - text: Reports
            - link "Lead Sources" [ref=e32] [cursor=pointer]:
              - /url: /lead-sources
              - img [ref=e33]
              - text: Lead Sources
        - generic [ref=e37]:
          - paragraph [ref=e38]: Administration
          - link "Employees" [ref=e40] [cursor=pointer]:
            - /url: /employees
            - img [ref=e41]
            - text: Employees
      - button "KA Kashif Admin Administrator" [ref=e55] [cursor=pointer]:
        - generic [ref=e56]: KA
        - generic [ref=e57]:
          - paragraph [ref=e58]: Kashif Admin
          - paragraph [ref=e59]: Administrator
        - img [ref=e60]
    - generic [ref=e62]:
      - banner [ref=e63]:
        - button [ref=e64] [cursor=pointer]:
          - img [ref=e65]
      - main [ref=e69]:
        - generic [ref=e70]:
          - generic [ref=e75]:
            - heading "Dashboard" [level=1] [ref=e76]
            - paragraph [ref=e77]: Welcome back, Kashif
          - generic [ref=e78]:
            - generic [ref=e80]:
              - generic [ref=e81]:
                - paragraph [ref=e82]: Total Leads
                - paragraph
              - img [ref=e84]
            - generic [ref=e90]:
              - generic [ref=e91]:
                - paragraph [ref=e92]: New Leads
                - paragraph
              - img [ref=e94]
            - generic [ref=e96]:
              - generic [ref=e97]:
                - paragraph [ref=e98]: Closed Won
                - paragraph
              - img [ref=e100]
            - generic [ref=e107]:
              - generic [ref=e108]:
                - paragraph [ref=e109]: Est. Value
                - paragraph [ref=e110]: $0
              - img [ref=e112]
          - generic [ref=e114]:
            - generic [ref=e115]:
              - heading "Pipeline" [level=3] [ref=e116]
              - img [ref=e119]:
                - generic [ref=e121]:
                  - generic [ref=e123]: New
                  - generic [ref=e125]: Qualified
                  - generic [ref=e127]: Proposal
                  - generic [ref=e129]: Closed Lost
                - generic [ref=e131]:
                  - generic [ref=e133]: "0"
                  - generic [ref=e135]: "0.75"
                  - generic [ref=e137]: "1.5"
                  - generic [ref=e139]: "2.25"
                  - generic [ref=e141]: "3"
            - generic [ref=e157]:
              - heading "By Source" [level=3] [ref=e158]
              - generic [ref=e160]:
                - img [ref=e161]
                - list [ref=e163]:
                  - listitem [ref=e164]:
                    - img [ref=e165]
                    - text: Website
                  - listitem [ref=e167]:
                    - img [ref=e168]
                    - text: Reference
                  - listitem [ref=e170]:
                    - img [ref=e171]
                    - text: Google Ads
                  - listitem [ref=e173]:
                    - img [ref=e174]
                    - text: Facebook
                  - listitem [ref=e176]:
                    - img [ref=e177]
                    - text: Phone Call
                  - listitem [ref=e179]:
                    - img [ref=e180]
                    - text: Instagram
                  - listitem [ref=e182]:
                    - img [ref=e183]
                    - text: LinkedIn
                  - listitem [ref=e185]:
                    - img [ref=e186]
                    - text: Trade Show
                  - listitem [ref=e188]:
                    - img [ref=e189]
                    - text: Old Client
                  - listitem [ref=e191]:
                    - img [ref=e192]
                    - text: Walk-in
                  - listitem [ref=e194]:
                    - img [ref=e195]
                    - text: Email Campaign
                  - listitem [ref=e197]:
                    - img [ref=e198]
                    - text: Other
          - generic [ref=e200]:
            - generic [ref=e201]:
              - heading "Recent Leads" [level=3] [ref=e202]
              - link "View all" [ref=e203] [cursor=pointer]:
                - /url: /leads
                - text: View all
                - img [ref=e204]
            - table [ref=e207]:
              - rowgroup [ref=e208]:
                - row "Title Customer Status Value Assigned To" [ref=e209]:
                  - columnheader "Title" [ref=e210]
                  - columnheader "Customer" [ref=e211]
                  - columnheader "Status" [ref=e212]
                  - columnheader "Value" [ref=e213]
                  - columnheader "Assigned To" [ref=e214]
              - rowgroup [ref=e215]:
                - row "AI Chatbot Integration Rabia Naz Closed Lost $15,000 Salman Ahmed" [ref=e216]:
                  - cell "AI Chatbot Integration" [ref=e217]:
                    - link "AI Chatbot Integration" [ref=e218] [cursor=pointer]:
                      - /url: /leads/15
                  - cell "Rabia Naz" [ref=e219]
                  - cell "Closed Lost" [ref=e220]:
                    - generic [ref=e221]: Closed Lost
                  - cell "$15,000" [ref=e222]
                  - cell "Salman Ahmed" [ref=e223]
                - row "Blockchain Solution Usman Ghani Closed Lost $120,000 Faisal Malik" [ref=e224]:
                  - cell "Blockchain Solution" [ref=e225]:
                    - link "Blockchain Solution" [ref=e226] [cursor=pointer]:
                      - /url: /leads/14
                  - cell "Usman Ghani" [ref=e227]
                  - cell "Closed Lost" [ref=e228]:
                    - generic [ref=e229]: Closed Lost
                  - cell "$120,000" [ref=e230]
                  - cell "Faisal Malik" [ref=e231]
                - row "Email Marketing Setup Ayesha Siddiqui Closed Won $5,000 Abdullah Ali" [ref=e232]:
                  - cell "Email Marketing Setup" [ref=e233]:
                    - link "Email Marketing Setup" [ref=e234] [cursor=pointer]:
                      - /url: /leads/13
                  - cell "Ayesha Siddiqui" [ref=e235]
                  - cell "Closed Won" [ref=e236]:
                    - generic [ref=e237]: Closed Won
                  - cell "$5,000" [ref=e238]
                  - cell "Abdullah Ali" [ref=e239]
                - row "Company Website Kamran Foster Closed Won $10,000 Salman Ahmed" [ref=e240]:
                  - cell "Company Website" [ref=e241]:
                    - link "Company Website" [ref=e242] [cursor=pointer]:
                      - /url: /leads/12
                  - cell "Kamran Foster" [ref=e243]
                  - cell "Closed Won" [ref=e244]:
                    - generic [ref=e245]: Closed Won
                  - cell "$10,000" [ref=e246]
                  - cell "Salman Ahmed" [ref=e247]
                - row "Learning Management System Prof. Tariq Jamil Proposal $65,000 Faisal Malik" [ref=e248]:
                  - cell "Learning Management System" [ref=e249]:
                    - link "Learning Management System" [ref=e250] [cursor=pointer]:
                      - /url: /leads/11
                  - cell "Prof. Tariq Jamil" [ref=e251]
                  - cell "Proposal" [ref=e252]:
                    - generic [ref=e253]: Proposal
                  - cell "$65,000" [ref=e254]
                  - cell "Faisal Malik" [ref=e255]
                - row "POS System Upgrade Mariam Bibi Proposal $18,000 Salman Ahmed" [ref=e256]:
                  - cell "POS System Upgrade" [ref=e257]:
                    - link "POS System Upgrade" [ref=e258] [cursor=pointer]:
                      - /url: /leads/10
                  - cell "Mariam Bibi" [ref=e259]
                  - cell "Proposal" [ref=e260]:
                    - generic [ref=e261]: Proposal
                  - cell "$18,000" [ref=e262]
                  - cell "Salman Ahmed" [ref=e263]
                - row "Hospital Management System Dr. Imran Shah Proposal $80,000 Abdullah Ali" [ref=e264]:
                  - cell "Hospital Management System" [ref=e265]:
                    - link "Hospital Management System" [ref=e266] [cursor=pointer]:
                      - /url: /leads/9
                  - cell "Dr. Imran Shah" [ref=e267]
                  - cell "Proposal" [ref=e268]:
                    - generic [ref=e269]: Proposal
                  - cell "$80,000" [ref=e270]
                  - cell "Abdullah Ali" [ref=e271]
                - row "Inventory Management System Zainab Noor Qualified $20,000 Faisal Malik" [ref=e272]:
                  - cell "Inventory Management System" [ref=e273]:
                    - link "Inventory Management System" [ref=e274] [cursor=pointer]:
                      - /url: /leads/8
                  - cell "Zainab Noor" [ref=e275]
                  - cell "Qualified" [ref=e276]:
                    - generic [ref=e277]: Qualified
                  - cell "$20,000" [ref=e278]
                  - cell "Faisal Malik" [ref=e279]
                - row "E-Commerce Platform Bilal Ahmad Qualified $45,000 Salman Ahmed" [ref=e280]:
                  - cell "E-Commerce Platform" [ref=e281]:
                    - link "E-Commerce Platform" [ref=e282] [cursor=pointer]:
                      - /url: /leads/7
                  - cell "Bilal Ahmad" [ref=e283]
                  - cell "Qualified" [ref=e284]:
                    - generic [ref=e285]: Qualified
                  - cell "$45,000" [ref=e286]
                  - cell "Salman Ahmed" [ref=e287]
                - row "SEO & Digital Marketing Nadia Hussain Contacted $8,000 Abdullah Ali" [ref=e288]:
                  - cell "SEO & Digital Marketing" [ref=e289]:
                    - link "SEO & Digital Marketing" [ref=e290] [cursor=pointer]:
                      - /url: /leads/6
                  - cell "Nadia Hussain" [ref=e291]
                  - cell "Contacted" [ref=e292]:
                    - generic [ref=e293]: Contacted
                  - cell "$8,000" [ref=e294]
                  - cell "Abdullah Ali" [ref=e295]
      - contentinfo [ref=e73]:
        - paragraph [ref=e74]: © 2026 Visionplus Technologies Pvt. All rights reserved.
  - generic [ref=e296]: "0"